### ISSUE TITLE
Combining SQL expressions with LINQ fails

### ISSUE THREAD

**Issue by FelschR** [Azure/azure-documentdb-dotnet#173]
Hi, I'm trying to execute a query with a dynamic property ("type").
My current solution looks like this:
`return client?.CreateDocumentQuery<T>(collection.DocumentsLink, "SELECT * FROM c WHERE c.type = \"" + documentType + "\"").Where(predicate).AsEnumerable();`

When it's executing I get the following error though:
`Microsoft.Azure.Documents.Linq.DocumentQueryException: Method 'AsSQL' is not supported. Only LINQ Methods are supported.`

Interestingly only the combination of the SQL Expression and Where() statement doesn't seem to work.
Also it only happens when I use `Expression<Func<T, bool>> predicate` instead of `Func<T, bool> predicate` but using the former would return an IEnumerable instead of an IQueryable.

Is this a bug? Is there an easy workaround to do this?

Thanks!

**Comment by FelschR** [comment]
I hope my description is understandable.
Let me know if you need more information about this issue.

**Comment by jonathanfishbein1** [comment]
@FelschR where you able to find a solution to this?  I have exactly the same issue

**Comment by bchong95** [comment]
Hi, 

Is predicate part of the supported LINQ operators?

https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sql-query#Linq

Scroll down to "List of supported LINQ operators".

Basically if you do something like `.Where(c => MyCustomFunction(c) == false)` this is going to cause an exception, since the Microsoft.Azure.Documents.Linq code does not know how to translate that to a SQL query. 

I think this post talks about a workaround which talks about filtering your query results client side with the actual .net LINQ library:

https://stackoverflow.com/questions/33839854/c-sharp-linq-any-not-working-on-documentdb-createdocumentquery

Please let me know if you still have this issue.

Thank you :)

**Comment by kirankumarkolli** [comment]
@FelschR please free to re-open if needed.

**Comment by krispenner** [comment]
@FelschR @jonathanfishbein1 I am trying to do the exact same thing as you guys, did either of you ever get an answer to this?

I would like to use a SqlQuerySpec to filter on a '_type' field first based on typeof(T).Name, then apply the predicate the caller passed in.  I don't want the caller to have to bother with filtering by document type (this is so I can easily share a single Collection across multiple types). 

`var query = _client.CreateDocumentQuery<T>(_collectionUri, new SqlQuerySpec("SELECT * FROM ROOT r WHERE r._type = @type", new SqlParameterCollection() { new SqlParameter("@type", typeof(T).Name) }), new FeedOptions { MaxItemCount = -1 }).AsDocumentQuery();`

**Comment by FelschR** [comment]
I ended up creating a custom base class with a type field that all my document classes inherit from so that I don't need to use an SQL string.
