### ISSUE TITLE
Cannot install core preview SDK via nuget into .NET core class library

### ISSUE THREAD

**Issue by rmmcgr** [Azure/azure-documentdb-dotnet#175]
In VS 2017 RC, a new .NET core class library I cannot install the document db SDK preview for .NET core.

Nuget output is: 
```
Package Microsoft.Azure.DocumentDB.Core 0.1.0-preview is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Package Microsoft.Azure.DocumentDB.Core 0.1.0-preview supports: netstandard1.6 (.NETStandard,Version=v1.6)
One or more packages are incompatible with .NETStandard,Version=v1.4.
```
I have the NETStandard version 1.6 package installed (it comes by default with this type of project).
Yet installing into an ASP.NET core project is fine.
Any ideas?

**Comment by rnagpal** [comment]
@rmmcgr There must be something in your project that enforces the .net standard version to 1.4 for any referenced Nuget package. Since we are on 1.6 it's complaining.

Are you sure that'a simple.net Core class library project in VS 2017 RC and not a special project say like UWP which enforces a lower .net standard version?

**Comment by kirankumarkolli** [comment]
@rmmcgr closing the issue. Feel free to re-open with repro.
