### ISSUE TITLE
ListKeys Support for DocumentDB Account?

### ISSUE THREAD

**Issue by solvingj** [Azure/azure-documentdb-dotnet#228]
Will this SDK ever get support for the ListKeys operation on a DocumentDB Account?

The swagger spec has it. 
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-documentdb/2015-04-08/swagger/documentdb.json

Alternatively, Is it possible to get the Autorest SDK for DocumentDB through Nuget?  I cannot find it.

**Comment by dmakwana** [comment]
The ListKeys operation will not be a part of this SDK. We are planning on releasing the Nuget package for a separate DocumentDB Management SDK generated by Autorest based on the swagger spec you mentioned. 

https://github.com/Azure/autorest/blob/master/docs/generating-a-client.md

**Comment by solvingJ** [comment]
Thanks! FYI, that day I generated it myself, and got it working, but look forward to a Nuget release.  One additional note, I recommend using the --addcredentials option when you generate for Nuget.   It cost me a few hours trying to figure out how to authenticate the client since that option is not on by default.

**Comment by solvingJ** [comment]
@dmakwana is there a place I can subscribe to find out when this is released?  I just know that it's usually not possible to provide an ETA for stuff like this.

**Comment by kirankumarkolli** [comment]
Its published as nuget package at https://www.nuget.org/packages/Microsoft.Azure.Management.DocumentDB.Fluent/
