### ISSUE TITLE
DateTimeOffset ignores offset during deserialisation, uses LOCAL TIME ZONE offset

### ISSUE THREAD

**Issue by GengeT** [Azure/azure-documentdb-dotnet#235]
We have the following poco in document Db, used to split out a date into JSON ticks and the ISO8601 date;

`"When": {
      "Date": "2017-04-03T10:57:56+01:00",
      "Ticks": 1491213476000
    },`

The Date field uses a direct set to an internal field on the GET, simple stuff.

However, when reading the document using the DocumentClient.CreateDocumentQuery it deserialises the date time offset without the offset, but instead uses the LOCAL TIME ZONE of the server to set the offset from UTC. Completely mind boggling.

Why the hell aren't you guys just doing a DateTimeOffset.Parse, or even better just use JSON.NET!

**Comment by GengeT** [comment]
It looks like this is a problem on the boundary of Json.NET and your SDK.

JsonConverter.DefaultSettings are being ignored when set in code, so you must have an explicit set of settings going into your JsonConvert.

If I deserialize from the document file locally there isn't a problem (with the correct JsonConverter default settings defined). However, DocumentClient.CreateDocumentQuery doesn't appear to respect the defaults set for JsonConverter.

**Comment by GengeT** [comment]
Sure, I could go to the ballache of storing a TimeZoneInfo and changing this now UTC date to the correct time zone, but that's processing I don't need to do if all I want to do is show the source data local time. That's already stored in the datetimeoffset... its kind of the point. If I was displaying in a TZ not of the source data then indeed I would expect to use a TimeZoneInfo (for example, if the user wants to view it in their time zone).

**Comment by GengeT** [comment]
Well, that's very odd. It now seems to be deserialising correctly, with no change to our code.

**Comment by GengeT** [comment]
So we did actually implement a TimeZoneInfo.ConvertTime using the sites time in the view model, which fixed it in our web UI. This is still as issue for DocumentDb however; DateTimeOffset should be treated as a DateTimeOffset.

**Comment by jackbond** [comment]
@GengeT I reported this issue months ago, and to be blunt, it would appear that certain members of the DocumentDb team are **ASTOUNDINGLY INCOMPETENT**. This is not an insult, this is a statement of fact. DateTimeOffset is the preferred Date object in .NET...

https://msdn.microsoft.com/en-us/library/bb384267(v=vs.110).aspx

**"These uses for DateTimeOffset values are much more common than those for DateTime values. As a result, DateTimeOffset should be considered the default date and time type for application development."**

The DocumentDb team should either fix this bug IMMEDIATELY, or publicly state that they do not support DateTimeOffset.

https://github.com/Azure/azure-documentdb-dotnet/issues/197

https://social.msdn.microsoft.com/Forums/azure/en-US/728ffe06-825e-40f1-aa87-b225062639bc/datetimeoffset-handling-very-serious-bug?forum=AzureDocumentDB

One workaround, which only works for retrieving a single document, is to manually handle the deserialization...

Uri documentUri = UriFactory.CreateDocumentUri("admn", "draw", $"{drawRefId}");
var response = await _DocumentClient.ReadDocumentAsync(documentUri).ConfigureAwait(false);

if (response.StatusCode == System.Net.HttpStatusCode.OK)
{
   using (StreamReader reader = new StreamReader(response.ResponseStream))
   {
      string json = await reader.ReadToEndAsync().ConfigureAwait(false);

      return JsonConvert.DeserializeObject<Draw>(json);
   }
}

**Comment by GengeT** [comment]
The bizarre thing is why has the community not made a big stink about this? Is not one else using DateTimeOffset? Is no one else doing anything remotely complex or date based (possibly due to poor Range based partition support) in DocumentDb? Maybe no one is actually using DocumentDb? Just completely perplexing, and yet REALLY EASY to fix. Just get the DateTimeOffset deserialisation using the JsonConvert to NOT specify Json settings, so it inherits the default global settings.

**Comment by arramac** [comment]
@jackhanbond

I'm from the DocumentDB team. Sincere apologies for the delay in responding and any gaps in communication. Let me explain what's happening here, our plans for addressing this, and how you can workaround this issue.

DocumentDB uses JSON.net for serialization and deserialization. Normally, JSON.net preserves the TimeZone offset when you do this across the conversion. However, when you are working with dynamic objects, JSON.net decides on whether a string is DateTime, DateTimeOffset, or string based on your serializer settings. By default, when a string parses to a DateTime or a DateTimeOffset, it chooses DateTime - which means that the offset information is dropped. See snippet below with just JSON.net:

``
public class Event
{
    [JsonProperty("id")]
    public String Id { get; set; }

    [JsonProperty("ts")]
    public DateTimeOffset TS { get; set; }
}

Event myEvent = new Event { Id = "Zero", TS = new DateTimeOffset(2017, 1, 1, 0, 0, 0, TimeSpan.Zero) };
string json = JsonConvert.SerializeObject(myEvent);


// You have the value of TS in local time
Event newEvent2 = JsonConvert.DeserializeObject<Event>(json);

// You have the correct value of TS with the UTC offset
Event newEvent = JsonConvert.DeserializeObject<Event>(json, new JsonSerializerSettings { DateParseHandling = DateParseHandling.DateTimeOffset });
``

Since DocumentDB works with any object type, internally all Documents are parsed as dynamic with the default Json serializer settings, which means that it is treated as DateTime. Note this is only on deserialization, the data as stored in DocumentDB will have the original timestamp with Offset. This is not mutated or changed by DocumentDB (you can verify via Fiddler). The change you see is only on read.

We are actively working on a change that will allow users to plug in custom Json serializer settings to the DocumentDB client. Since this is a fairly large change since DocumentDB uses JSON conversion in a number of places including metadata for collections and databases, unfortunately we cannot provide a stop-gap hotfix for DateTimeOffset parsing. 

However, there are a couple of workarounds we had suggested to your questions - 1. storing the DateTimeOffset as a string and 2. implementing a custom JsonConverter that ensures the offsets are deserialized as you want it.

Thanks again for using DocumentDB. And once again, sorry about the delay. Please email us at askdocdb@microsoft.com, and we can discuss in more detail over a call and help you with a solution.

**Comment by GengeT** [comment]
Thanks @arramac. We've had to implement our own date wrapper to handle storing as JSON / Unix based ticks, to allow range lookups anyway. The actual DateTimeOffset is stored as a property of this wrapper; so we updated this today to store offset under another property, used in conjunction with the Ticks when reading into our code. It does the job for now.

Re: the fix, it seems to me you could just set the JsonSerializerSettings to parse the date time strings as DateTimeOffset, using "RoundTrip" as opposed to "Local"? Any chump still using DateTime in their data model (rather than DateTimeOffset) deserves everything they get!

We do love DocumentDb; just so easy to scale, takes away a lot of the pain of storage as long as the data is suitable (unstructured, high volume). And OMG TimeToLive is a real time saver / worker maintenance saver. The new auto-partition / 250GB collection abstraction is cool (rather expensive) but a bit limited for most data models, unless you have clear partition key candidates which are hashes (and not ranges).

**Comment by arramac** [comment]
@GengeT glad you have a workaround, and happy to hear you link DocumentDB :)

We did consider changing the default to DateTimeOffset, but as you can imagine, it's a change that can break existing applications (the SDK is downloaded ~900k times on Nuget), so we want to be careful and address in a backwards-compatible way. 

Hash is more elastic and supports high throughput because we can distribute data evenly, and this evenness + parallelism generally outweighs the benefits of range partitioning. You can also devise hybrid schemes where a bucket of range values hash to a single value. Happy to chat offline about partition key schemes and how you can map between range and hash partitioning.

**Comment by jackbond** [comment]
Hi everyone,

I reported an issue here

https://social.msdn.microsoft.com/Forums/azure/en-US/735edf3c-83e3-4a19-98c1-ab23b1be2b05/unable-to-load-dll-microsoftazuredocumentsserviceinteropdll?forum=AzureDocumentDB

and here

https://github.com/Azure/azure-documentdb-dotnet/issues/312

several days ago, and have received no response. I realize you guys may have a lot on your plate, but quite frankly, your level of community engagement COMPLETELY SUCKS.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by GengeT** [comment]
@jackbond I wonder if you and I are the only ones who use DocumentDb! Or at least use it for anything more exciting that very simple data models.

**Comment by jackbond** [comment]
@GengeT They released a new version of the Nuget library Microsoft.Azure.DocumentDB.Core yesterday. What does it do? Who the f**k knows, they certainly don't communicate anything. Oh here look at their Azure blog, https://azure.microsoft.com/en-us/blog/tag/documentdb/ Wow! Really stellar guys, the last post was in April. Do they really have NOTHING going on worth communicating? Oh wait, maybe this is the link, https://azure.microsoft.com/en-us/blog/tag/azure-cosmos-db/ Ah much better, a post in June.

**Comment by ealsur** [comment]
@jackbond The SDK version changes are updated on the SDK docs pages. This is the one for [.Net Core](https://docs.microsoft.com/en-us/azure/cosmos-db/documentdb-sdk-dotnet-core) and this for [.Net Full Framework](https://docs.microsoft.com/en-us/azure/cosmos-db/documentdb-sdk-dotnet).

Hope it helps 😄

**Comment by jackbond** [comment]
@ealsur Thanks for the update. It is nice to see that the DateTimeOffset issue was resolved in the 1.15 release. It would be great if GitHub was more of a one stop shop for information. As it stands, I've reported a MAJOR BUG with the Microsoft.Azure.DocumentDB.Core 1.4.0 Nuget, here and on the Microsoft forums, and as near as I can tell, no one on the team seems to monitor those forums or here on a regular basis. And if they do, it seems like...

THEY COULD GIVE A FLYING FUCK

Seriously, what the fuck is wrong with the DocumentDB client team? The DateTimeOffset issue should have never made it past a v1 Alpha. And when someone does report a bug, you have to raise hell to highlight it. Does anyone on that team have any pride in their work?

**Comment by pcoppney** [comment]
@arramac  Has there been any progress on this?

**Comment by arramac** [comment]
@pcoppney custom JsonSerializerSettings is supported as of SDK 1.16.0. Can you please try setting that when you read/write these objects. You need something like: new JsonSerializerSettings { DateParseHandling = DateParseHandling.DateTimeOffset })

**Comment by pcoppney** [comment]
I am using .net core and version 1.7.1 of Microsoft.Azure.DocumentDB.Core.  Which SDK are you talking about?

**Comment by jcageman** [comment]
I have had this issue now on multiple places in azure... azure functions, cosmos.. Why is the datetimeoffset problem not being taken seriously? Everytime the problem is in the json serializers..

**Comment by pvanroos** [comment]
What is the workaround for Microsoft.Azure.Cosmos lib v3.5.1?  As everyone has mentioned, it serializes in Cosmos correctly, it's only when you pull the document back that you get it as a DateTime.

**Comment by JohnLTaylor** [comment]
Have you tried the following:
            JsonConvert.DefaultSettings = () => new JsonSerializerSettings
            {
                DateFormatHandling = DateFormatHandling.IsoDateFormat,
                DateFormatString = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.fffffffK",
                DateParseHandling = DateParseHandling.DateTimeOffset
            };

This should work and without the DateParseHandling it will not parse correctly

**Comment by dluc** [comment]
Encountered the same issue, please fix this. For now this workaround is helping:

```csharp
JsonConvert.DefaultSettings = () => new JsonSerializerSettings
{
    DateParseHandling = DateParseHandling.DateTimeOffset,
    DateTimeZoneHandling = DateTimeZoneHandling.Utc
};
```
