### ISSUE TITLE
Intermittent exception : Resource Not Found"

### ISSUE THREAD

**Issue by PhaniJaddu** [Azure/azure-documentdb-dotnet#373]
Hello Team, 

Have  a web job which in turn run every day and delete the documents in a collection and insert the fresh data i.e document in a collection which are not partitioned . Have observed that i do not see any issue with process but some time i do get the below exception and data in the collection will be in corrupt state . Error message is not of much help and as am not using the partition , still do not understand that why this will look for the document in the partition . 

could be great if someone can help me the possible causes for this . Please find the activity id and details 

****Error**** 

{"Errors":["Resource Not Found"]} ActivityId: 132ca535-b6a9-40a5-b257-29791ee9cf7f, Request URI: rntbd://by3prdddc01-docdb-1.documents.azure.com:14053/apps/28284a68-9708-4ee8-97da-dc5bfad115b9/services/6ebac9e6-3bcd-4370-9d62-1918d46a80cc/partitions/e0ff8834-8fa6-4f3b-8ea6-c4dd97b34845/replicas/131527654382594212p/Message: {"Errors":["Resource Not Found"]} ActivityId: 132ca535-b6a9-40a5-b257-29791ee9cf7f, Request URI: rntbd://by3prdddc01-docdb-1.documents.azure.com:14053/apps/28284a68-9708-4ee8-97da-dc5bfad115b9/services/6ebac9e6-3bcd-4370-9d62-1918d46a80cc/partitions/e0ff8834-8fa6-4f3b-8ea6-c4dd97b34845/replicas/131527654382594212p/

**Comment by chrisparkeronline** [comment]
I'm having some what similar problem with what I posted yesterday. Mine is happening with a collection that is partitioned. Even when you provide the partition key and the id, you will still get that error in a web job/azure function.

**Comment by kirankumarkolli** [comment]
@PhaniJaddu are you enumerating the documents and then deleting them? Is it possible that parallel clients (web job instances) are trying to do the same and over-stepping on each other?

Also CosmosDB does support TTL (TileToLive) and evict item after the time. You can create documents with TTL aligned and this will be automatically taken care of.

**Comment by PhaniJaddu** [comment]
@kirankumarkolli  : I forgot to mention that we have only one instance of the web job running , we are using stored procedure to delete the documents , so we send some list of the documents to stored procedure and then it will delete and then we pick some more and then it will delete .. this will be keep on happening till there are no records left

**Comment by kirankumarkolli** [comment]
Retry might also cause this issue.

Ideal in your case would be to leverage TTL capability which would cleanup automatically.

**Comment by rnagpal** [comment]
@PhaniJaddu @chrisparkeronline : If you can provide a standalone repro for this, I can try repro'ing this on my end. At the minimum, please send me your sample code you are using, so that I can see if there is anything with the code that could cause this. Can you add some logging to your stored procedure when a delete is successful(log the id of the document) and also log the id of the document that throws Resource Not Found, to see if you only deleted the document that you are trying to delete again?

You could consider deleting the collection itself and then recreating the collection(that will implicitly delete all documents) and will be more efficient. 

@PhaniJaddu To answer your question on the word "partition", that's an internal term we use for the single unit of storage in our system. It has nothing to do with your collection being partitioned or not.

**Comment by rnagpal** [comment]
@chrisparkeronline : Never mind, I saw your earlier post. That's a different issue that seems to have been resolved by you.

**Comment by kirankumarkolli** [comment]
Please re-active is possible with a repo details.
