### ISSUE TITLE
Microsoft.Azure.Graphs - Gremlin - Allow partitioning for edges

### ISSUE THREAD

**Issue by rd0nz** [Azure/azure-documentdb-dotnet#388]
NuGet `Microsoft.Azure.Graphs 0.3.1-preview`
Cosmos `Azure Cosmos DB Emulator 1.19.102.5`

## Note
This issue has only been verified using the Cosmos DB Emulator.

## Issue 
Setting a partition-key property while creating an edge in Gremlin throws an exception. Cosmos DB however allows setting partition-keys for edges through REST. 

Unknown to me is if there is support for setting the `_vertexPartition` explicitly.

## Reproduction

Using the following Gremlin to create an edge between vertices with an attempt to define the partition key of the edge:
```
 g.V()
   .hasId('{entityX.id}').has('partitionKey','{entityX.partition}')
   .addE('some-edge').property('partitionKey', 'entity-to-entity')
   .to(g.V().hasId('{entityY.Id}').has('partitionKey','{entityY.Partition}'))
```

Resulting in:
```
Microsoft.Azure.Graphs.Common.GraphRuntimeException : Gremlin Query Execution Error: The inserted edge has a partition property, but the property value is different from that of the source vertex.
   at Microsoft.Azure.Graphs.Runtime.EdgeDocumentHelper.
```

## Suggested solution
Allow setting a partition on an edge and introducing a `_vertexPartition` on the edge document being created:

```
POST https://127.0.0.1:8081/dbs/db/colls/col/docs HTTP/1.1
x-ms-documentdb-partitionkey: ["entity-to-entity"]
x-ms-date: Tue, 21 Nov 2017 14:33:45 GMT
authorization: type%3dmaster%26ver%3d1.0%26sig%3djzJ3O4LQXADU6%2fIVopC%2bhHLclmmghABdjaHwJec9FiU%3d
x-ms-session-token: 0:771
Cache-Control: no-cache
x-ms-consistency-level: Session
User-Agent: documentdb-dotnet-sdk/1.19.1 Host/32-bit MicrosoftWindowsNT/10.0.15063.0
x-ms-version: 2017-11-15
Accept: application/json
Host: 127.0.0.1:8081

{
 "label" : "some-edge",
 "id" : "c57c184f-44c0-47dc-9f8b-66bf3ff807bc",
 "_sink" : "4e503f9a-841d-499d-8cee-c40ccfc200c0",
 "_sinkLabel" : "NativeVertex",
 "_sinkPartition" : "entityYPartition",
 "_vertexId" : "56397178-d1c1-4c1b-bd57-eed5725a55b3",
 "_vertexLabel" : "NativeVertex",
 "_vertexPartition" : "entityXPartition",
 "_isEdge":true,
 "partitionKey":"entity-to-entity"
}
```

And consequently allow to query on edges inside specific partitions:
```
g.V()
   .hasId('{entityX.Id}').has('partitionKey', '{entityX.Partition}')
   .outE('some-edge').has('partitionKey', 'entity-to-entity')
   .inV()
```

```
POST https://127.0.0.1:8081/dbs/db/colls/col/docs HTTP/1.1
x-ms-documentdb-partitionkey: ["entity-to-entity"]
x-ms-continuation: 
x-ms-documentdb-isquery: True
x-ms-max-item-count: -1
x-ms-documentdb-query-iscontinuationexpected: True
x-ms-documentdb-populatequerymetrics: True
authorization: type%3dmaster%26ver%3d1.0%26sig%3dQMIZkdHHNm4re9BJGgQVs8dH5xirKG8oNI1YVoQ8Jr8%3d
Cache-Control: no-cache
x-ms-consistency-level: Session
User-Agent: documentdb-dotnet-sdk/1.19.1 Host/32-bit MicrosoftWindowsNT/10.0.15063.0
x-ms-version: 2017-11-15
Accept: application/json
Content-Type: application/query+json
Host: 127.0.0.1:8081

{ 
 "query" : 
   "
     SELECT * FROM E_0 
     WHERE E_0._vertexId IN ('56397178-d1c1-4c1b-bd57-eed5725a55b3') 
     AND IS_DEFINED(E_0._isReverse) = false 
     AND E_0[\"partitionKey\"] IN ('entity-to-entity') 
     AND (E_0[\"label\"] = 'some-edge')
   "
}
```
Edit: small fixes

**Comment by olivertowers** [comment]
There is currently no support for this in CosmosDB Graph.

Would it be possible to provide a use-case for this? In what circumstances would you need this control and to what end? I can see benefits in some circumstances, but it will be helpful if you can provide concrete examples for your scenario.

Also could you add this ask as a suggestion to our [user feedback forum](https://feedback.azure.com/forums/263030-azure-cosmos-db?category_id=321991).

**Thoughts on this behavior:**

The main concern with allowing partitioning of edges is related to performance and non-determinism in the query execution engine. If the query  does not have a partition to scope the vertex->edge traversal op to, then it will do a cross partition query. Today this only happens if the initial query step doesn't provide a partition key. For example: 

    g.V().has('notpk', 'foo').outE()...

- `V()` doesn't include a predicate on partition key so it would do a cross partition query and performance would depend on the slowest partition and whether 'notpk' property is indexed.
- `outE()` will resolve with a partition scoped query since the query engine can assume edges are in the same partition as the vertices resolved in the `V()` step. 
- All other traversal operations will translate to partition scoped queries. 

As you suggested, providing an edge partition key predicate in the traversal op could mitigate this. However the onus would be on you to keep track of which partitions you are interested in and apply them accordingly through-out your query traversal to avoid the perf/charge hit.

The major pitfall for users who aren't as aware of partitions, or aren't keeping track of partitions is that they may end up throttling themselves from sub-optimal queries. This is already possible today, but may increase the likelihood, in addition to complicating the story for performance best practices.

**A possible solution:** 

- For queries, assume that edges and source vertex are co-located in the same partition (i.e. default behavior), but if the edge traversal predicate includes a partition key, then this supersedes the assumption.

- Similarly for edge write-ops, if the edge does specify a partition key property, then write to that partition, otherwise, write to source vertex partition.

**Comment by olivertowers** [comment]
Closing this issue. There aren't any plans to change layout of edges in partitions and we aren't seeing enough demand for this feature.

**Comment by krishkg** [comment]
I believe this need to be addressed internally to Cosmosdb, so the queries for incoming vertexes will take less RUs. please consider this
