### ISSUE TITLE
Paging - There is no active document producer

### ISSUE THREAD

**Issue by nlavri** [Azure/azure-documentdb-dotnet#398]
Hello,
I'm trying to implement a paging for mvc app.
I do two http queries to my mvc app. 
Each time the controller action makes a query to a azure db.
The second db query uses a ResponseContinuation property from the first request query result via FeedOptions.
Then I get an exception that "There is no active document producer".
Is there any configuration parameters to enable continuation?

**Comment by nlavri** [comment]
Seems that i need to wrap the token into "array".
` feedOptions.RequestContinuation = $"[{requestContinuation}]";`

Is it expected behavior?  FeedResponse.ResponseContinuation is a json string that is not an array.

**Comment by kirankumarkolli** [comment]
@bchong95 could you please look into this.

**Comment by bchong95** [comment]
This is a bug. What was happening is that you hit the code path that checks to see if the continuation token is valid. If it is invalid it print the token and we also trace the state. Unfortunately when we are tracing the state there is a chance that there is no document producer (which is guarenteed for your case where you are resuming form a continuation token). Basically the useful exception message got squashed by this obscure exception message. This will be fixed in the next SDK release.

**Comment by bchong95** [comment]
This got resolved in the latest SDK. I will close the issue. Please feel free to reopen if this happens again.
