### ISSUE TITLE
Cannot use reserved word "value" as an alias

### ISSUE THREAD

**Issue by jpascale** [Azure/azure-documentdb-dotnet#419]
I'm using the documentdb dependency for node and I have the following query, which doesn't work:

`SELECT c.id as value FROM c`

and the error message i'm getting is:
```
start: 15
end: 20
code: SC1001
message: "Syntax error, incorrect syntax near 'value'."
```

but this one works:

`SELECT c.id as valuee FROM c`

Is there any way of escaping the `value` reserved word?

The output i'm trying to get is the following:

```
[ { value: 'id1' },
  { value: 'Id2' },
  { value: 'Id3' },
  { value: 'Id4' },
  ... ]
```

Thanks in advance.

**Comment by sboshra** [comment]
You can't escape 'value' here because it's an alias and the grammar requires it to be an identifier.
However, you could rewrite the projection to be an explicit JSON object where the alias becomes a property name.

So the query above would look something like this:
SELECT VALUE {'value': c.id }
FROM c

**Comment by kirankumarkolli** [comment]
Resolving the issue, please re-open in-case needed.
