### ISSUE TITLE
[Gremlin API] Better way to return error messages

### ISSUE THREAD

**Issue by BenjaBobs** [Azure/azure-documentdb-dotnet#452]
## Problem
I want to return error messages when a query attempts to do something it can't, such as adding an edge between two entities but one of the entities doesn't exist.
It is currently possible, but I have to jump through some hoops to get there.

## Hacky solution
The current way I return error messages is to coalesce on a union of choose-steps with checks.
Example of adding a `worksAt` edge from a `person` to a `company` and then returning the `company`: 
```groovy
g.inject(0).coalesce(
    coalesce(
        union(
            choose(g.V("6087ec4c-c531-475e-8ef9-9282ae77232f").hasLabel("company").store('company').count().is(0), 
                constant('Company[6087ec4c-c531-475e-8ef9-9282ae77232f] does not exist.'), 
                constant(0).is(1)
            ),
            choose(g.V("6ca14ec9-8ddd-47e8-815e-22aed18f96db").hasLabel("person").store('person').count().is(0), 
                constant('Person[6ca14ec9-8ddd-47e8-815e-22aed18f96db] does not exist.'), 
                constant(0).is(1)
            ),
            choose(g.E().hasLabel("worksAt").where(outV().is("6ca14ec9-8ddd-47e8-815e-22aed18f96db").and().inV().is("6087ec4c-c531-475e-8ef9-9282ae77232f")).store('ExistingWorksAt').count().is(gt(0)), 
                constant('Cannot add edge Person[6ca14ec9-8ddd-47e8-815e-22aed18f96db]--(worksAt)-->Company[6087ec4c-c531-475e-8ef9-9282ae77232f] because it already exists.'), 
                constant(0).is(1)
            )
        )
    ).local(fold()).project('errors'),
    select('person').property("worksAtId", "6087ec4c-c531-475e-8ef9-9282ae77232f").union(
        addE("worksAt").to(select('company')).inV(), 
        select('ExistingWorksAt').drop()
    )
)
```

I start by injecting a 0 to start with a single traverser and so that I can *start* with a coalesce step.
The first traversal in that coalesce-step will return either an array of error messages or nothing.
This enables me to do my query afterwards only if no error messages were generated.

Inside the error checking part, I do a union of choose-steps.
Each one checks for the existence of some entity or edge, and then stores the result.
The choose-steps return `constant(0).is(1)` in order to be able to coalesce if no error messages were generated.
I then pack all the error messages in `errors` if there are any, and continue if there are not.

Lastly I do the actual query, with the entities/edges found during error checking.

## Clean solution
[???](https://xkcd.com/844/)
I don't know how to best make this more intuitive and readable but I have some suggestions.
* Allowing coalesce to be a starting step, `inject.(0)` could be omitted, which would increase readability-
* A step for returning nothing, e.g. `empty()` could replace `constant(0).is(1)`, which would increase readability.
* A step for checking existence, e.g. `exists()` would make it easier to use choose-steps like `choose(not(exists(g.V('id').store('entityName'))), constant('entity was not found'), consant('entity was found'))`
* Allowing omitting the last argument of the [choose-step](http://tinkerpop.apache.org/docs/current/reference/#choose-step) would make it so I don't have to return an empty result such as `constant(0).is(1)`.

If I am going about this completely the wrong way, I'm would very much appreciate suggestions. Thanks for your time.

**Comment by kirankumarkolli** [comment]
@olivertowers please look into this.

**Comment by olivertowers** [comment]
I think it's best to project a simple state structure as the response rather than using error messages. My approach would be fairly similar to what you were aiming for though:

```
    g.inject(0).
        coalesce(__.V('6ca14ec9-8ddd-47e8-815e-22aed18f96db'), constant('none')).as('s')
        project('source', 'target', 'edge').
            by(select('s')).
            by(coalesce(__.V('6087ec4c-c531-475e-8ef9-9282ae77232f'), constant('none'))).
            by(coalesce(select('s').outE().hasLabel('worksAt').where(inV().id().is('6087ec4c-c531-475e-8ef9-9282ae77232f')), constant('none'))).
       as('state').
       choose(
           select('edge').is('none'),
           union(select('state'), addE('worksAt').from('source').to('target')),
           select('state'))
```

The project() part of the query will return map structure of form:
[source: <>, target: <>, edge: <>]

And for incomplete data, theses results are expected:
```
[source:none, target:none, edge:none]

```
```
[source:v[6ca14ec9-8ddd-47e8-815e-22aed18f96db], target:none, edge:none]
```
```
[source:v[6ca14ec9-8ddd-47e8-815e-22aed18f96db], target:v[6087ec4c-c531-475e-8ef9-9282ae77232f], edge:none]

```

The query is also source vertex centric, such that it won't attempt to query for the edge if the source vertex doesn't already exist. This will make it faster especially if you end up switching to a partitioned collection. 

The choose() part of the query will test the existence of 'edge' in the map and if it doesn't exist it will create the missing edge. In this case the state map structure will be returned, and the second result will include the newly added edge, eg.

```
==>[source:v[6ca14ec9-8ddd-47e8-815e-22aed18f96db], target:v[6087ec4c-c531-475e-8ef9-9282ae77232f], edge:none]
==>[id:4c8eb8bd-0a5d-4b21-b713-077a0c7aa882,label:worksAt,type:edge,inVLabel:Company,outVLabel:Persion,inV:6087ec4c-c531-475e-8ef9-9282ae77232f,outV:6ca14ec9-8ddd-47e8-815e-22aed18f96db]
```
Not sure I understand why you are using drop() at the end of your example but the above seems like it would meet most of your requirements.

Regarding making changes to the Gremlin step grammar/semantics, CosmosDB Gremlin follows Apache Tinkerpop specifications, and in general we only deviate in cases where we don't or can't support certain steps, or when we extend the steps for CosmosDB specific features.

I'd recommend going to the [gremlin-users](https://groups.google.com/forum/#!forum/gremlin-users) mailing list or [stackoverflow](https://stackoverflow.com/questions/tagged/gremlin) to ask general gremlin query/structure questions so that it is visible to contributors to Tinkerpop and other gremlin experts.

**Comment by BenjaBobs** [comment]
Thanks, that query is a lot more readable.
The drop in the end was to make the edge unique.
