### ISSUE TITLE
IDocumentClient is not Mockable

### ISSUE THREAD

**Issue by CreepyGnome** [Azure/azure-documentdb-dotnet#462]
There appears to be no easy way to Mock the IDocumentClient for a number of reasons. Some of which is because not all return values are interfaces, or easily created objects making it difficult to impossible to create setups. Plus its difficult to impossible due to the complexity of the interface with 202 methods and properties that have difficult to determine dependencies upon each other.

How did you guys plan for people who want to use DocumentDB test their code? Because even if we place the IDocumentClient behind a repository pattern the repository will still be dependent on having an IDocumentClient injected into its constructor.  Because of your design of IDocumentClient I will have code that cannot be unit tested as I can mock MY repository so everything that uses my repository can be tested however I cannot test my repository itself because of IDocumentClient . A repository around IDocumentClient isn't as simple as others due to its design so it would be nice to have unit tests cover it and not have to rely on integration tests that happen after the code is checked in to find a bug.

Are there plans to simplify IDocumentClient for a possible near future 2.0 release?

**Comment by davetheunissen** [comment]
Hey @CreepyGnome, this is something that I across recently in a project that I was working on. In short, you can mock IDocumentClient using the repository pattern and the Moq framework. This will allow you to unit test your repository functionality while abstracting away the actual document client database calls. This works well with a generic repository pattern too.

I've put together an example @ https://github.com/davetheunissen/RepositoryMoq to show what this could look like. In this example, `DocumentRepository` encapsulates the DocumentClient functionality and `ProductRepository` would be your repository. There is a xUnit `ProductRepositoryTest` unit test which shows how to wire this all up.

There are a couple of little things to note. 
- The methods in the base repository class that encapsulate your document client calls must be marked as virtual in order for Moq to proxy the function.
- The `ProductRepository` extends the `DocumentRepository` so if you are wanting to test the functionality of your repository, you will need to mock the concrete class so that the methods get invoked by your tests. `var mockProductRepository = new Mock<ProductRepository>(It.IsAny<IDocumentClient>());`

Let me know if this works for your use case.

**Comment by CreepyGnome** [comment]
Hi @davetheunissen,

I was mocking IDocumentClient and the setups were getting crazy due to overly complex return objects that should be Interfaces themselves. I had to use reflection to create the results for setups for the mocks and that is a big code smell. If it was just one maybe two tests that needed it fine. But it is ALL tests that would need it.

I looked at your example and its very simple and only has to worry about the Document type and setting the ID. You need more than that to properly mock IDocumentClient for a full CRUD based and generic based Repository.  

The following is just what I came across before I gave up that required some form of reflection to set private or protected values or to construct:

- Document
- ResourceResponse
- Database
- DatabaseAccount
- DocumentServiceResponse

I was about 1/3 the way to a working In-Memory IDocumentClient implementation to use as "Mock" before I realized that was crazy once I saw 202 methods and properties I would have to implement and that testing the Mock would be something I would need to do too now.

I also had to re-implement some methods that are on DocumentClient implementation in my Repository base that should have been in the IDocumentClient interface and where never added.  (For example: CreateDatabaseIfNotExistsAsync and CreateDocumentCollectionIfNotExistsAsync since the repo should control both of those two functions).

I appreciate your attempt to help and the example, however, this is a deep issue that has been around since the first release of IDocumetnClient (even before Cosmos DB). Many people over the years have asked about this on StackOverflow and other forums. So I finally figured it deserves a formal Issue in the Github for it to get an official answer from Microsoft about its future going forward. As to make it testable it will need to have a few breaking changes and a few non-breaking changes however it's the breaking changes that will force this to be at best a 2.0 release.

**Comment by davetheunissen** [comment]
@CreepyGnome, no problem. Having a look at the DocumentServiceResponse I see it's not possible to mock out the http status response because it's set internally. 

According to a comment on another task, this is the official issue being tracked by the dev's.
https://github.com/Azure/azure-documentdb-dotnet/issues/342

Good luck!

**Comment by CreepyGnome** [comment]
@davetheunissen thanks for the reference I was searching for an existing one and I missed that one.  Probably because of the title.  Now that it is linked I will close this and monitor the other one.
