### ISSUE TITLE
Graph library can't parse simple Array properties with an existing Document base collection

### ISSUE THREAD

**Issue by jstawski** [Azure/azure-documentdb-dotnet#524]
This is a cross post from [here](https://stackoverflow.com/questions/50683837/graph-library-cant-parse-simple-array-properties-with-an-existing-document-base).

We have an existing CosmosDb collection that we use with the SQL API. We want to start using the Graph API against this collection. Using the `Microsoft.Azure.Graphs` NUGET version 0.3.1-preview and performing the simple Gremlin query `g.V()` throws an Invalid Cast Exception:

Invalid cast from 'System.String' to 'Newtonsoft.Json.Linq.JObject'.

After lots of trial and error, we narrowed it down to a property array of string values:

```
{
  "Roles": [ "user", "admin" ]
}
```

Converting this property to an object or removing this property fixes the issue, of course that is not a viable solution.

Is this a bug on the Graph SDK, on the Cosmos Db engine, on Gremlin, or simply not doable in Graph in general?

How do we solve this issue?

**Comment by BenjaBobs** [comment]
Can it be converted to a JArray instead of a JObject? I have had luck distinguishing values, objects and arrays, but I don't know how the underlying data structure is if you're using the gremlin api on data created with the sql api.

**Comment by jstawski** [comment]
We are not converting anything, just doing a plain gremlin query and getting the error. This is data created by the SQL Api. We did find references specifying that it is doable and supported.

**Comment by olivertowers** [comment]
@jstawski CosmosDB Gremlin API is supported as a Gremlin Server endpoint, and `Microsoft.Azure.Graphs` was deprecated. You can follow this [guide ](https://docs.microsoft.com/en-us/azure/cosmos-db/create-graph-dotnet) to create a Gremlin server endpoint and connect to it via Gremlin.NET (other gremlin driver clients are supported in different languages as well).

As @BenjaBobs mentioned, Gremlin API expects the underlying document to follow a specific structure  for vertex properties, otherwise they will not be exposed to the query engine or included in the projected results. However, properties not in this format should be ignored rather than cause errors.

Please try switching to the Gremlin endpoint/Gremlin.NET, and if the errors persist please provide repro steps so we can investigate further (example document that was inserted, the gremlin query that returned an error).

**Comment by jstawski** [comment]
Thanks for the feedback. That worked, closing now.
