### ISSUE TITLE
CountAsync() does not honor partition key

### ISSUE THREAD

**Issue by stephenschwan** [Azure/azure-documentdb-dotnet#535]
We changed from multiple collection to single collection w/partition keys.  Normal query operations work as expected with partition keys.  We noticed the CountAsync() method does not honor partition key and will count everything in the collection which matches the filter criteria:

return await _docDbClient.CreateDocumentQuery<T>(_collectionUri, new FeedOptions() { PartitionKey = new PartitionKey(typeof(T).Name) })
                .Where(filter)
                .CountAsync();

If we add an additional filter for our partition key, then it works as expected.

**Comment by moderakh** [comment]
@stephenschwan 

some questions:

1. from PartitionKey(typeof(T).Name) }) are you intending to use the class type name as your partition key value?
2. Which version of SDK are you using?
3. Version of .Net and if that's Standard or .Net Core
4. OS Platform (and 32 or 64 bit)
5. Can you please rewrite this to be a string query rather than doing LINQ like usage. something like this: CreateDocumentQuery(., partitionKey, "SELECT value count(c) FROM c where c.x = 'your value' and c.yourpartitionkey = 'your partitionkeyvalue'"). Can you please try this and see if this works?

**Comment by stephenschwan** [comment]
1. Yes, our class name is the partition key for our collection
2. 1.10.0
3. .NET standard 2.0
4. 64bit, latest on Azure App Service


**just pass partition key in feedoptions - Doesn't work:**
await _docDbClient.CreateDocumentQuery<T>(_collectionUri, new FeedOptions() { PartitionKey = new PartitionKey(typeof(T).Name) })
                .Where(filter)
                .CountAsync();

**Add partition key in where clause Works:**
await _docDbClient.CreateDocumentQuery<T>(_collectionUri, new FeedOptions() { PartitionKey = new PartitionKey(typeof(T).Name) })
                .Where(filter)
                .Where(t => t.EntityType == typeof(T).Name) /*partitionkey*/
                .CountAsync();

**SQL query with partition key in feedoptions - Works:**
_docDbClient.CreateDocumentQuery(_collectionUri, "SELECT count(1) from c where c.tenantGroupId='bb022401-3ab3-483b-8c98-6ae203332d3f'", new FeedOptions() { PartitionKey = new PartitionKey(typeof(T).Name) }).AsDocumentQuery();

Let me know - normal queries honor the partition key in feedoptions - just CountAsync does not.

**Comment by moderakh** [comment]
@stephenschwan  I think your SDK (1.10.0) is stale.
Can you please upgrade to the latest version 1.21.1
https://www.nuget.org/packages/Microsoft.Azure.DocumentDB/

**Comment by stephenschwan** [comment]
Our assembly is .net standard 2.0 -  the one mentioned above is 45?  So we are using this package: [https://www.nuget.org/packages/Microsoft.Azure.DocumentDB.Core/1.9.1].

I downloaded the 2.0 preview and the issue is fixed. [https://www.nuget.org/packages/Microsoft.Azure.DocumentDB.Core/2.0.0-preview]

thanks!

**Comment by vmarsen** [comment]
> We changed from multiple collection to single collection w/partition keys. Normal query operations work as expected with partition keys. We noticed the CountAsync() method does not honor partition key and will count everything in the collection which matches the filter criteria:
> 
> return await _docDbClient.CreateDocumentQuery(_collectionUri, new FeedOptions() { PartitionKey = new PartitionKey(typeof(T).Name) })
> .Where(filter)
> .CountAsync();
> 
> If we add an additional filter for our partition key, then it works as expected.

Same issue here, but with Microsoft.Azure.DocumentDB v2.2.1 installed in a .NET Framework 4.6.2 project.

The following code gives problems:
            var queryOptions = new FeedOptions
            {
                MaxItemCount = -1,
				EnableCrossPartitionQuery = false,
				PartitionKey = new PartitionKey(partitionKeyValue)
            };
			
            return Client.CreateDocumentQuery<T>(UriFactory.CreateDocumentCollectionUri(DatabaseName, CollectionName), queryOptions)
                .Where(predicate).CountAsync();

If we use the CountAsync() on a partitioned db and we set the partitionKey value via the queryOptions but not via the predicate, then it fails sometimes (not always unfortunately).  The result will not taking into account the partitionkey.
We can solve the problem by replacing the CountAsync() by a ToList().Count, but this is not a valid solution since the RU count is higher then. So it seems that it has something to do with the CountAsync() method.

**Comment by landau07** [comment]
Same issue as vmarsen mention.

We use Where partition== ourPoartition predicate eventually.
Should be in the same efficient cost in terms of performance as passing it in the OptionsFeed?

Thanks,
Yaron
