### ISSUE TITLE
Posible bug in select statement

### ISSUE THREAD

**Issue by eNepper** [Azure/azure-documentdb-dotnet#76]
When I run this select I get 0 results: SELECT ST_DISTANCE(l.Geometry, { "type": "Point", "coordinates": [1,1]}) AS dist FROM l WHERE l.dist > 1

But if I change the query to look like this: SELECT ST_DISTANCE(l.Geometry, { "type": "Point", "coordinates": [1,1]}) AS dist FROM l WHERE ST_DISTANCE(l.Geometry, { "type": "Point", "coordinates": [1,1]}) > 1
I get the expected result.

**Comment by arramac** [comment]
@eNepper this is by design. Like in relational SQL, the query is evaluated in FROM-WHERE-SELECT-ORDER BY order, so a property you define in a SELECT cannot be referenced in WHERE. More details here: https://msdn.microsoft.com/en-us/library/azure/dn782250.aspx

Why you get zero results vs. an error is because DocumentDB doesn't have a schema to bind against, and allows any property reference like "dist" because documents can have mixed schemas.
